CONFIG_ZMK_STUDIO=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Must explicitly set 2 peripherals (left + right)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# 2 peripherals + 5 BT profiles = 7
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

CONFIG_SPEED_OPTIMIZATIONS=y # zephyr config
